export const itemList =  [
  {
    id: 1,
    title: "Ganyu",
    img:'ganyuu.jpg',
    desc: "Фигурка Гань-Юй",
    category: "figurka",
    price: "999",
  },
  {
    id: 2,
    title: "Hu Tao",
    img:'hutao.jpg',
    desc: "Фигурка Ху-тао",
    category: "figurka",
    price: "999",
  },
  {
    id: 3,
    title: "Miko",
    img:'miko.jpg',
    desc: "Фигурка Мико",
    category: "figurka",
    price: "999",
  },
  {
    id: 4,
    title: "Raiden",
    img:'raidenS.jpg',
    desc: "Фигурка Райден",
    category: "figurka",
    price: "999",
  },
  {
    id: 5,
    title: "Xiao",
    img:'xiao.jpg',
    desc: "Фигурка Сяо",
    category: "figurka",
    price: "999",
  },
  {
    id: 6,
    title: "Zhongli",
    img:'chu.jpg',
    desc: "Фигурка Джунли",
    category: "figurka",
    price: "999",
  },
]